spring:
  application:
    name: Hello Spring
  jdbc:
    datasource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql:///cloud2021?serverTimezone=GMT%2B8
      username: root
      password: 123456

server:
  port: 8999

