server:
  port: 80
spring:
  application:
    name: spring-cloud-consumer-feign-order80
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:7001/eureka
logging:
  level:
    com.springcloudalibaba.consumer.openfeign.FeignAdminLogService: debug